version: 0.2

phases:
  pre_build:
    commands:
      # Docker daemon startup
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 377773544554.dkr.ecr.eu-west-1.amazonaws.com
      # Set local variables
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      # Adding our own job libraries
      # Repository URI should be defined inside the buildspec env variables (for dev/prod/test) in the AWS codebuild project
      - docker build -t dev-trend-analysis .
      - docker tag dev-trend-analysis:latest 377773544554.dkr.ecr.eu-west-1.amazonaws.com/dev-trend-analysis:latest
      #- docker build -t $REPOSITORY_URI:latest .
      #- docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      #- docker push $REPOSITORY_URI:latest
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push 377773544554.dkr.ecr.eu-west-1.amazonaws.com/dev-trend-analysis:latest
      - docker push 377773544554.dkr.ecr.eu-west-1.amazonaws.com/dev-trend-analysis:$IMAGE_TAG
artifacts:
  files:
      - imageDetail.json

